### ISSUE TITLE
The file '/opt/vitis_ai/compiler/arch/DPUCAHX8H/U50/arch.json' not found

### ISSUE THREAD

**Issue by AltiumChou** [Xilinx/Vitis-AI-Tutorials#10]
I got the error message when I do the step 6 "source 6_compile.sh".

Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/bin/vai_c_tensorflow", line 186, in <module>
    compiler = VAI_TensorFlow_Frontend(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/bin/vai_c_tensorflow", line 76, in __init__
    with  open(args.arch) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vitis_ai/compiler/arch/DPUCAHX8H/U50/arch.json'

It seem like the file "arch.json" did not generate when I start this docker.
How should I do to fix that? thx

**Comment by lorantszabo98** [comment]
Hi!
I'm facing the same problem. Did you find any solution?
Documentation says: "You can find thearch.json files for those platforms in /opt/vitis_ai/compiler/arch." But I can't see any files there.
Should I reinstall the whole VitisAI?
Thanks

**Comment by JianmingTONG** [comment]
Same Question here

**Comment by JianmingTONG** [comment]
This is the solution link https://forums.xilinx.com/t5/AI-and-Vitis-AI/Vitis-AI-Compiler-ZCU104-json/td-p/1129551.

The arch.json files are located after we launch the docker.
