### ISSUE TITLE
Error Running MNIST source 6_compile_zcu102.sh

### ISSUE THREAD

**Issue by gjkunde** [Xilinx/Vitis-AI-Tutorials#14]
Hello,

I am getting the following error:

(vitis-ai-tensorflow) Vitis-AI /workspace > source 6_compile_zcu102.sh 
-----------------------------------------
COMPILE ZCU102 STARTED..
-----------------------------------------
[INFO] parse raw model     : 12%|█▎        | 1/8 [00:00<00:00, 2714.76it/s]                  
[INFO] Namespace(inputs_shape=None, layout='NHWC', model_files=['./build/quantize/deploy_model.pb'], model_type='tensorflow', out_filename='./build/compile_zcu102/customcnn_org.xmodel', proto=None)
[INFO] tensorflow model: build/quantize/deploy_model.pb
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/bin/xnnc-run", line 33, in <module>
    sys.exit(load_entry_point('xnnc==1.3.0', 'console_scripts', 'xnnc-run')())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/__main__.py", line 194, in main
    normal_run(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/__main__.py", line 178, in normal_run
    in_shapes=in_shapes if len(in_shapes) > 0 else None,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/xconverter.py", line 131, in run
    xmodel = CORE.make_xmodel(model_files, model_type, _layout, in_shapes)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/core.py", line 104, in make_xmodel
    model_files, layout, in_shapes=in_shapes, model_type=model_t
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 97, in to_xmodel
    model_name, raw_nodes, layout, in_shapes, model_fmt, model_type
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 161, in create_xmodel
    xmodel = cls.__create_xmodel_from_tf1(name, layers, layout, in_shapes)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 243, in __create_xmodel_from_tf1
    xmodel_name, layout, layers, const_layer_dict, super_const_dict, in_shapes
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 1847, in __generate_xmodel
    ), f"[ERROR] TF Conv2d requires two inputs: actual: {bottom}."
AssertionError: [ERROR] TF Conv2d requires two inputs: actual: ['images_in'].
**************************************************
* VITIS_AI Compilation - Xilinx Inc.
**************************************************

**Comment by dingguodong-826** [comment]
Hello, I have the same problem. If you have solved it, please tell me how to do it. Thank you

**Comment by lioneldaniel** [comment]
This link may help: https://forums.xilinx.com/t5/AI-and-Vitis-AI/val-c-tensorflow-error-for-MNIST-Classification-Tensorflow/m-p/1190229/highlight/true#M6369
